name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Formatted?
      working-directory: go
      run: |
        gofmt -l .
        test -z `gofmt -l .`

    - name: Build
      working-directory: go
      run: go build -v ./...

    - name: Test
      working-directory: go
      run: go test -v ./...

    - name: Benchmark
      working-directory: go
      run: go test -bench . ./...

    - name: Lint (staticcheck)
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        install-go: false
        version: "2023.1.6"
        working-directory: go
